# Generated by Django 5.1.1 on 2024-10-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio_url',
            new_name='profile_url',
        ),
    ]
